@startuml
'https://plantuml.com/class-diagram

MoveWords <|-- Move
MoveWords <|-- Parser
MoveWords <|--- Game
Move <|- Parser
Parser <|-- Game
Move <|-- Game

class Game {
-parser : Parser
+Game()
-welcome()
-printHelp()
-computerMove()
-printWinner(int who)
-printMoves(Move player, Move computer)
-processMove(Move move)
+playGame()
+main()
}

class Move {
-move : String
+Move()
+Move(String move)
+getMove()
+isUnknown()
+beats(Move other)
}

class MoveWords {
+EMPATE : int
+GANA : int
+PIERDE : int
-validMoves : String[]
-validCommands : String[]
-rnd : Random
+MoveWords()
+isValidMoveCommand(String value)
+randomMove()
+showMoves()
+showCommands()
+showWords()
-getIndex(String value)
+checkWinner(String first, String second)
}

class Parser {
-moves : MoveWords
-reader : Scanner
+Parser()
+showCommands()
+newRandomMove()
+getMove()
}

@enduml